[[htslib]]
arch = "aarch64"
git-tree-sha1 = "cb671fa2ccfa9726b5e2bc195dae2c918c279fd7"
os = "macos"

    [[htslib.download]]
    sha256 = "48697ef603f785fa36d9518e88f1034219f85c9ef8e8e3b850d6abda28caabf2"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.aarch64-apple-darwin.tar.gz"
[[htslib]]
arch = "aarch64"
git-tree-sha1 = "09f11e192ffd843033f61d539b01647a71c6f1ce"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "7fc361e2559ecbfb1f626f663830ec2161e6408e5793fce84450d104014a16c6"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.aarch64-linux-gnu.tar.gz"
[[htslib]]
arch = "aarch64"
git-tree-sha1 = "66b70048861d7262ad805408495668e5195d505d"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "ed8b091d5be8184455026edaccd45d3efa9dc54dd89bb44bba76c9200ad4d579"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.aarch64-linux-musl.tar.gz"
[[htslib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "06d3c7d472c08ed69b608f54dd5ca78eca74f2d9"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "e6571b4f376b35cf6223665deeb7a2c5e3633dd13bfd984cb218f6b831dee60f"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.armv6l-linux-gnueabihf.tar.gz"
[[htslib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ee4b216182374f5d0d90f551ad8241952f9bd83"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "16acb41bcc3738cb70255ef5c7552b589dfc6b9545945d4fbf87450196e195c6"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.armv6l-linux-musleabihf.tar.gz"
[[htslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eba913a40fabf346a7100257e5b368ec1e82c782"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "6c8e24aba3e38415b6b79044b49267954c0a764c9a66dfe9c7cc674a94d8b8c7"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.armv7l-linux-gnueabihf.tar.gz"
[[htslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54983c301b17f9cbcaae994c30319ed7d821f680"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "ef169abe6f115955dff3a05d7b391d9eb3972a98942d18f265f7703b6b7616f0"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.armv7l-linux-musleabihf.tar.gz"
[[htslib]]
arch = "i686"
git-tree-sha1 = "5360f44d8cba8703cbe234078941e31941b8ae95"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "96d38b92a35f6dfef5b4356843df1a13131f2384fb0f39535c1497d0e3af8eb7"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.i686-linux-gnu.tar.gz"
[[htslib]]
arch = "i686"
git-tree-sha1 = "13334af255948208341edad1cf9ebd2bcbb3508a"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "6d53fce069522f39e258090d1ad457f65274bcd3eb2a4402af3404165de1eae3"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.i686-linux-musl.tar.gz"
[[htslib]]
arch = "powerpc64le"
git-tree-sha1 = "e659c4b2b69fd9e5ae45af6644ed8f40f3fa5a51"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "4220ca9d1708b06c13baef3e58c4940fb6c3acb4da75bdc64fb447c1f8435016"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.powerpc64le-linux-gnu.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "2b329371458e38d611f25673d1e5b7c324ad006a"
os = "macos"

    [[htslib.download]]
    sha256 = "ca145d2a671e06e6b69ee9d7b2f394f396ee48876ba08e50122e250b9e741076"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.x86_64-apple-darwin.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "25cc9c75c3cb850c4449426f21235a3ac7a55746"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "c073fc4126c26756d44f5fa6769f35e091481c395498ead6a3d360750d96e162"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.x86_64-linux-gnu.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "e794ff9453bf4db4c557a0431b4b3e8afc4e5eae"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "778b551855d4423b36dbccd22532760ec25b8060597d12098fbb11035fe86779"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.x86_64-linux-musl.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "c117147facd314d4543bd491bc20d5fb3cb39cfc"
os = "freebsd"

    [[htslib.download]]
    sha256 = "da36ce1df73172a5531cf07bdbbc9df98b78869284902f37fc5e0cc025c77e3e"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.19.1+0/htslib.v1.19.1.x86_64-unknown-freebsd.tar.gz"
