[[htslib]]
arch = "aarch64"
git-tree-sha1 = "341366ccc2dadb789b1d2dc779e6dfdde5555416"
os = "macos"

    [[htslib.download]]
    sha256 = "39e5d7af1dc399e8e75cce2fa2d3c586e7329312c4e018f476a59318e6789a79"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.aarch64-apple-darwin.tar.gz"
[[htslib]]
arch = "aarch64"
git-tree-sha1 = "d1ecd4aa12624dd46efb249194cb291659001de6"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "fb454fbd02974dd0c9b7f74413a2d73627ccf1b400f1a73af0eb763faf745374"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.aarch64-linux-gnu.tar.gz"
[[htslib]]
arch = "aarch64"
git-tree-sha1 = "8654bdac590d9a2712d80cdc4a5f130c644b65f4"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "41d8d3f84052366887690edb42e22ff24de0488539ceba2a3978c361b97b185f"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.aarch64-linux-musl.tar.gz"
[[htslib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b59a6d5d0299c049ea10e57665b8c308e725685a"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "5095a0ee91057bf7d1d27b90f57746b9fe268606feb7bb0a7e6bea297617bdf8"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.armv6l-linux-gnueabihf.tar.gz"
[[htslib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "19d02eecb8dee17bbd02035594c3d534b2db7143"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "2ce3cd6fd7141ae7a76ea56c4489f51e2dc86fce985c5f7168f879462783feef"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.armv6l-linux-musleabihf.tar.gz"
[[htslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "29aa3472ee5a21a8d22ab4ca6a3b7bcbe4f9cafe"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "d646577f1599537974656a02de46bb2cc9061a3a0909f26deb0475a7b8568a39"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.armv7l-linux-gnueabihf.tar.gz"
[[htslib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a334658d101400695924e321f9b075d1f578ea3c"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "67e2af2f619ae277c6d6c5ecbf57d04292e7f165048042e193f58477ae2e324d"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.armv7l-linux-musleabihf.tar.gz"
[[htslib]]
arch = "i686"
git-tree-sha1 = "bcdc693c24c68214c7d50d5925782f54c2d48ae8"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "fa7a5c17fc11e7a76a3f008385820a5e8539dcaa8179c326c444124c15122675"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.i686-linux-gnu.tar.gz"
[[htslib]]
arch = "i686"
git-tree-sha1 = "934597c790c46e52a40c9137a37a55394d967a36"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "877e45d9d99f7d950d73c33f80675cdb8c44c9bca12451bb4f95e827c2995631"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.i686-linux-musl.tar.gz"
[[htslib]]
arch = "powerpc64le"
git-tree-sha1 = "ce6c84e8fc689b153992487872eb8e44955bfa71"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "4164086417cab639be77eb20a3522303bc86529ded4ad47960d7314de2b6e793"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.powerpc64le-linux-gnu.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "c5cff86bdd3dbf9de4e24e3b5fc0bce4e2003799"
os = "macos"

    [[htslib.download]]
    sha256 = "968a2664a1b9866def2538f16c2219b5a7bfd962875de4d36919ce81b84569b3"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.x86_64-apple-darwin.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "da92f250167a9c0aba86fcd43a27c52dfc723f49"
libc = "glibc"
os = "linux"

    [[htslib.download]]
    sha256 = "a76b66e7dd28e68743d9510644cd02852a06a94519415a6401ddf0afdce4f1ad"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.x86_64-linux-gnu.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "4ed50241e60edefa8f894b70b94bd827c739d6f1"
libc = "musl"
os = "linux"

    [[htslib.download]]
    sha256 = "9a1080126321f5747694c793853258514ee4e710c709207e7851fa52adb56f9d"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.x86_64-linux-musl.tar.gz"
[[htslib]]
arch = "x86_64"
git-tree-sha1 = "99de074b134f942ee41f9c04cc7e5f097dc7f317"
os = "freebsd"

    [[htslib.download]]
    sha256 = "c3985e58f6e62d7c2259666ed10176dd31b275abed9bcb2187092765c8d68886"
    url = "https://github.com/JuliaBinaryWrappers/htslib_jll.jl/releases/download/htslib-v1.14.0+0/htslib.v1.14.0.x86_64-unknown-freebsd.tar.gz"
